### ISSUE TITLE
No module named 'termios'

### ISSUE THREAD

**Issue by xyombo** [gojuukaze/tty_menu#2]
```
 Successfully installed tty-menu-1.0.3

```

但是提示 No module named 'termios'

搜了一下，结果有点多，请问应该按照哪个？ setup.py 里也没有找到相应的依赖

https://pypi.org/search/?q=termios

**Comment by gojuukaze** [comment]
这是py自带的包，只有在UNIX环境下才有。  
因此这个项目也支持linux，mac osx。
