### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by hec9527** [gojuukaze/tty_menu#3]
`pip `无法安装了，大佬维护一下

**Comment by hec9527** [comment]
![image](https://user-images.githubusercontent.com/28671232/72255603-2255a100-3642-11ea-835f-bdbb51c787e2.png)

**Comment by gojuukaze** [comment]
pypi不知道为啥被墙了，可以换个源，或者直接从github安装：
```
pip install git+https://github.com/gojuukaze/tty_menu.git@master
```
